# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib robusTest, .registration=TRUE
#' @importFrom Rcpp sourceCpp
NULL

max2D_cpp <- function(x, y) {
    .Call(`_robusTest_max2D_cpp`, x, y)
}

#' @useDynLib robusTest, .registration=TRUE
#' @importFrom Rcpp sourceCpp
NULL

spearmanCore <- function(x, y) {
    .Call(`_robusTest_spearmanCore`, x, y)
}

