# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib robusTest, .registration=TRUE
#' @importFrom Rcpp sourceCpp
NULL

#' Compute the test statistic for the robust independence test of Kolmogorov-Smirnov's type
#'
#' Compute the maximum distance between the joint empirical cumulative
#' distribution function (e.c.d.f.) and the product of the marginals e.c.d.f.
#' multiplied by square root of n
#' @param x,y the two sequences of vector that are applied to the function.
#' @export
max2D_cpp <- function(x, y) {
    .Call('_robusTest_max2D_cpp', PACKAGE = 'robusTest', x, y)
}

